{
 "title": "Telemetria DC",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "ACL block spoofing Statistics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "acl_interface_input_acl_filter_entry_statistics_matched_packets{entry_sequence_id=\"20\"}",
     "legendFormat": "iface {{interface_interface_id}} ACL block spoofing"
    }
   ]
  },
  {
   "title": "Multicast Packets (por Interface)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "interface_statistics_in_broadcast_packets{subscription_name=\"srl-if-stats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumo CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "platform_control_cpu_total_instant{subscription_name=\"srl-system-performance\"}",
     "legendFormat": "{{source}}"
    }
   ]
  }
 ]
}